
// ******************************

let arr =['tamil']
let rev=''

let firstword = arr[0]

for(let i=firstword.length-1; i>=0; i--){
    rev+=firstword[i]
}

arr[0]=rev

console.log(arr);

//******************************** */









// //----------------------------------------
// let stri ='tamil'
// let rev=''
// let arr=[]

// for(let i=stri.length-1; i>=0 ; i--){
//     rev+=stri[i]
// }

// arr.push(rev)
// console.log(arr);
// //------------------------------------------





// let str = 'tamil'
// let reversed=''

// for(let i=str.length-1; i>=0; i--){
//     reversed+=str[i]
// }
// console.log(reversed);
// //palindrome
// if(str==reversed){
//     console.log('it is palindrome');
// }else{
//     console.log('not');
// }

// ---------------------------










// // ---------------------------

// arr=[14,3,4,6,7,2]
//  const rev = arr[0].toString().split('').reverse().join('')
//  arr.splice(0,1,Number(rev))
//  console.log(arr);
 
//  //notes
//  //number to string - toString
//  //string to number - Number(stringName), parseInt(stringName), parseFloat(stringName),    +stringName (this method called unary operator)

// // ---------------------------





// // ---------------------------
// arr=[1,3,4,6,7,2]
// const rev = arr.reverse()
// console.log(rev);
// // ---------------------------



// ------------------------------

// let arr =["hii","het"]
// let arr1=[...arr]
// let r=arr1[0].split('').reverse().join('')
// arr1.splice(0,1,r)

// console.log(arr);
// console.log(arr1);



// -----------------
// arr = 'Hiii'
// const arr1 = arr.split('').reverse().join('')
// console.log(arr1);
